---
- hosts: appui-latest:appd-latest:appcapi-latest:appjs-latest:appui-prod:appd-prod:appcapi-prod
  connection: local
  gather_facts: no
  vars:
    tf_profile: latest
    tf_region: "us-west-2"
    env: "dev-2"
    delete_action: false
  tasks:
    - name: check if secret key already exists
      command: "aws secretsmanager describe-secret --profile {{ ssm_aws_profile }} --region {{ tf_variables.Region }} --secret-id {{ ssm_name }}"
      register: _aws_secret_check
      become: no
      ignore_errors: yes
    
    - name: Output the secret
      debug:
        var: _aws_secret_check
      when: not _aws_secret_check.failed

    - name: Delete Secrets
      shell: "aws secretsmanager delete-secret --force-delete-without-recovery --secret-id {{ ssm_name }} --profile {{ ssm_aws_profile }} --region {{ tf_variables.Region }}"
      when: delete_action|bool

