- name: Start secretmanager deploy steps - check for template secret
  command: "aws secretsmanager  get-secret-value --profile {{ ssm_template_aws_profile }} --region {{ tf_variables.Region }} --secret-id {{ ssm_template }}"
  register: _aws_secret_template_check
  become: no
  
- name: Set new Secret configurations
  set_fact:
    ssm_configs: "{{ (_aws_secret_template_check.stdout | from_json )['SecretString'] | from_json | combine(ssm_updated_values) }}"

- name: check if secret key already exists
  command: "aws secretsmanager describe-secret --profile {{ ssm_aws_profile }} --region {{ tf_variables.Region }} --secret-id {{ ssm_name }}"
  register: _aws_secret_check
  become: no
  ignore_errors: yes

- name: Create new AWS Secrets Manager Secret
  command: "aws secretsmanager create-secret --profile {{ ssm_aws_profile }} --region {{ tf_variables.Region }} --name {{ ssm_name }} --secret-string '{{ ssm_configs | to_json }}'"
  register: _aws_create_secret
  when: _aws_secret_check.failed

- debug:
    msg: "Created new AWS Secrets Manager Secret: {{ ssm_name }}"
  when: _aws_secret_check.failed

- name: Update existing AWS Secrets Manager Secret
  command: "aws secretsmanager update-secret --profile {{ ssm_aws_profile }} --region {{ tf_variables.Region }} --secret-id {{ ssm_name }} --secret-string '{{ ssm_configs | to_json }}'"
  register: _aws_update_secret
  when: not _aws_secret_check.failed

- debug:
    msg: "Updated existing AWS Secrets Manager Secret: {{ ssm_name }}"
  when: not _aws_secret_check.failed

# - debug:
#     msg: "{{ _aws_update_secret }}"
#   when: not _aws_secret_check.failed
